### ISSUE TITLE
SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by brianlukoff** [Meteor-Community-Packages/meteor-autoform-themes#11]
I'm getting an error when starting an app using 2.0.0-rc.0 of `communitypackages:autoform-bootstrap3` running RC2 of Meteor 3.0:

```
I20240605-16:16:26.282(-5)? error on boot.js packages/communitypackages_autoform-bootstrap3.js:15
I20240605-16:16:26.282(-5)? export const AutoFormThemeBootstrap3 = {}
I20240605-16:16:26.282(-5)? ^^^^^^
I20240605-16:16:26.282(-5)?
I20240605-16:16:26.282(-5)? SyntaxError: Unexpected token 'export'
I20240605-16:16:26.282(-5)?     at new Script (node:vm:116:7)
I20240605-16:16:26.282(-5)?     at createScript (node:vm:268:10)
I20240605-16:16:26.283(-5)?     at Object.runInThisContext (node:vm:316:10)
I20240605-16:16:26.283(-5)?     at /tools/static-assets/server/boot.js:414:32
I20240605-16:16:26.283(-5)?     at /tools/static-assets/server/boot.js:503:13
I20240605-16:16:26.283(-5)?     at AsyncLocalStorage.run (node:async_hooks:346:14)
I20240605-16:16:26.283(-5)?     at /tools/static-assets/server/boot.js:502:37
I20240605-16:16:26.283(-5)?     at Function.run (/Users/brian/workspaces/perusall/app/.meteor/local/build/programs/server/tools/tool-env/profile.ts:315:14)
I20240605-16:16:26.283(-5)?     at startServerProcess (/tools/static-assets/server/boot.js:501:17)
I20240605-16:16:26.283(-5)?     at Object.<anonymous> (/tools/static-assets/server/boot.js:508:2)
I20240605-16:16:26.283(-5)?     at Object.<anonymous> (/tools/static-assets/server/boot.js:512:4)
I20240605-16:16:26.283(-5)?     at Module._compile (node:internal/modules/cjs/loader:1369:14)
I20240605-16:16:26.283(-5)?     at Module.Mp._compile (/tools/static-assets/server/runtime.js:78:21)
I20240605-16:16:26.283(-5)?     at Object.Module._extensions..js (/tools/static-assets/server/runtime.js:112:21)
I20240605-16:16:26.283(-5)?     at Module.load (node:internal/modules/cjs/loader:1206:32)
I20240605-16:16:26.283(-5)?     at Module.Mp.load (/tools/static-assets/server/runtime.js:35:31)
I20240605-16:16:26.285(-5)? packages/communitypackages_autoform-bootstrap3.js:15
I20240605-16:16:26.285(-5)? export const AutoFormThemeBootstrap3 = {}
I20240605-16:16:26.285(-5)? ^^^^^^
I20240605-16:16:26.285(-5)?
I20240605-16:16:26.285(-5)? SyntaxError: Unexpected token 'export'
I20240605-16:16:26.285(-5)?     at new Script (node:vm:116:7)
I20240605-16:16:26.285(-5)?     at createScript (node:vm:268:10)
I20240605-16:16:26.285(-5)?     at Object.runInThisContext (node:vm:316:10)
I20240605-16:16:26.285(-5)?     at /tools/static-assets/server/boot.js:414:32
I20240605-16:16:26.285(-5)?     at /tools/static-assets/server/boot.js:503:13
I20240605-16:16:26.285(-5)?     at AsyncLocalStorage.run (node:async_hooks:346:14)
I20240605-16:16:26.285(-5)?     at /tools/static-assets/server/boot.js:502:37
I20240605-16:16:26.285(-5)?     at Function.run (/Users/brian/workspaces/perusall/app/.meteor/local/build/programs/server/tools/tool-env/profile.ts:315:14)
I20240605-16:16:26.285(-5)?     at startServerProcess (/tools/static-assets/server/boot.js:501:17)
I20240605-16:16:26.285(-5)?     at Object.<anonymous> (/tools/static-assets/server/boot.js:508:2)
I20240605-16:16:26.285(-5)?     at Object.<anonymous> (/tools/static-assets/server/boot.js:512:4)
I20240605-16:16:26.285(-5)?     at Module._compile (node:internal/modules/cjs/loader:1369:14)
I20240605-16:16:26.285(-5)?     at Module.Mp._compile (/tools/static-assets/server/runtime.js:78:21)
I20240605-16:16:26.286(-5)?     at Object.Module._extensions..js (/tools/static-assets/server/runtime.js:112:21)
I20240605-16:16:26.286(-5)?     at Module.load (node:internal/modules/cjs/loader:1206:32)
I20240605-16:16:26.286(-5)?     at Module.Mp.load (/tools/static-assets/server/runtime.js:35:31)
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
```

To reproduce, create a plain Meteor 3.0 RC2 app (`meteor create <appname> --release 3.0-rc.2`) and then add `communitypackages:autoform-bootstrap3` to the `packages` file.

**Comment by jankapunkt** [comment]
@brianlukoff can you please check if this is resolved with version 2.0.0?

**Comment by brianlukoff** [comment]
It is working with 2.0.0 -- thanks!
